### ISSUE TITLE
Cookie consent and privacy policy

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#15]
This is activated on the site.

@ulric-wilson you can configure both the cookie consent message and the policy page from within Site Settings.

**Comment by ulric-wilson** [comment]
what is outcome of non-consent to cookies?

**Comment by joeaudette** [comment]
There are essential cookies such as the authentication cookie which are not subject to consent. Ironically, cookie consent is also tracked with a cookie but that is considered an essential cookie.

Without consent we generally should not allow any third party cookies to be set and we should not load any 3rd party resources into the page if they set cookies.

The system will configure google analytics to not use any cookies if there is no consent but page views can still be tracked anonymously.

Also there is a built in AddThis.com support for social sharing which is also disabled without cookie consent because it also adds 3rd party tracking cookies.

**Without cookie consent we should not render the twitter widget** because that adds 3rd party tracking cookies. This shows another benefit of the server side approach to twitter which would allow us to show the twitter feed without adding any cookies and therefore we don't have to hide it if there is no consent.

The rules should apply to any other 3rd party scripts if we add any later.

If a user grants consent but later revokes it, it is important to understand that we cannot delete 3rd party cookies, the web browser doesn't give us any ability to do that for security reasons. But, for example since we would then not load the twitter widget those cookies would not be tracking users on our site because cookies only get sent if we request a remote resource like javascript or images or css. However those cookies would now be there and tracking on any other sites the user visits that have a twitter widget, unless the other site is also obeying rules about consent.

**Comment by CrispinF** [comment]
@johawker @jonparsonsjncc you might want to review this issue and check everything's in order.
