### ISSUE TITLE
Example page with Twitter feed

### ISSUE THREAD

**Issue by CrispinF** [jncc/chm-website#4]
JNCC would like to embed a twitter feed, so we have agreed to provide a sample page with the mark-up to show a twitter feed, which JNCC editors can then adapt.

**Comment by joeaudette** [comment]
there is a ready built twitter widget for cloudscribe, developed by a community member and available as a nuget package. source code here :https://github.com/jasongaylord/gaylordsolutions.TwitterWidget
example site using it here: https://www.jasongaylord.com/

**Comment by CrispinF** [comment]
@joeaudette ah yes I remember seeing that... does it provide any advantages over simply pasting in the Twitter embed timeline code, e.g. as we have here combined with other content on a CMS page... https://hbsmrweb-exmoor.esdm.co.uk/ 
(scroll down a bit, and the client is playing around with settings)

**Comment by joeaudette** [comment]
The main advantage is it is a server side retrieval of tweets so it doesn't require the twitter javascript and therefore doesn't include the 15 cookies and other things twitter wants to add to the page.
It also means you have complete control over rendering

![twitter-cookies](https://user-images.githubusercontent.com/101627/52741562-9f484880-2fa3-11e9-9f6a-df8afd36e8e1.jpg)

**Comment by CrispinF** [comment]
OK that's quite some baggage, and things to explain in cookie/privacy policy! And I guess the server-side fetch might result in faster page load too, so long as the Twitter API is fast.

I guess a potential disadvantage might be that is and when Twitter change their API this requires developer-level resolution, while using their embed code would simply going and get their latest.

All we're asked for here under this contract is a sample, so if it's very quick to add Jason's widget we could put that on one page and the Twitter one on another and ask JNCC to decide which they would like to use, bearing in mind what we've said here about cookies etc.

**Comment by joeaudette** [comment]
in order to add the server side twitter it will require an api key and secret which can be obtained in their developer portal https://developer.twitter.com/en/docs/basics/developer-portal/overview

the only advantage of the js widget is it doesn't require that.

But have a look at their cookie consent
https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview

![twitter-cookies2](https://user-images.githubusercontent.com/101627/52744547-fa316e00-2faa-11e9-938d-02bf555cc54b.jpg)

**Comment by joeaudette** [comment]
I think to do correct gdpr, a twitter widget should not be rendered on a page until after a user accepts cookie consent of the site, otherwise we are pushing 3rd party tracking cookies on them without consent. So that means really we need to make a content template for the widget in order to be able to control that, it can't be done in regular content, the script is either there or not there in regular content. Similarly we don't allow disqus comments on a page without cookie consent, but that is handled different since it is a built in feature not something that goes into content.

**Comment by joeaudette** [comment]
I've created a custom content template for the home page based on the 1-4 section template but adding what is needed for a twitter widget and to not show it unless there is cookie consent.
I figured the 1-4 section template gives the most flexibility for home page content and layout.

Initial deployment is not finished yet but once it is done we need to create the home page with that template.

Note that unfortunately if a user revokes our cookie consent after initially accepting it and after all the 3rd party cookie have been set by twitter, it doesn't remove those 3rd party cookies and we have no possible way to remove them since they are not under our control.

**Comment by joeaudette** [comment]
The site is now up and running at https://chm.esdm.co.uk/ with a twitter widget on the home page.
Note that once other home page content is created, if needed we can re-position the twitter widget in the content template, at the moment it is below all editable content.

Still, my recommendation is for someone to get us api key and consumer secret and then we can setup the server side approach which is much more GDPR friendly than the javascript widget and allows more control over styling it to match whatever theme we use,

**Comment by CrispinF** [comment]
Assigning this one to @ulric-wilson now for decisions on Twitter feed.
